### ISSUE TITLE
KH freezes when "Creating Highlights Table"

### ISSUE THREAD

**Issue by edo-jan** [noembryo/KoHighlights#46] opened 2024-10-31 23:40 UTC
I am having a strange issue. I loaded a large number of books under Loaded / Highlights view. The grid loaded ok, even though it was very unresponsive to navigate. I then closed KH.  Now when I am trying to open the tool it tries to load the last open view and the program freezes while trying to load the grid again.  I am not sure if there is a way to stop the process and re-open the program in say Loaded or Sync view? 
![2024-10-31_193321](https://github.com/user-attachments/assets/af0dfb6c-5638-4b1f-be20-149ed5da3c6e)

**Comment by noembryo** [comment] 2024-11-01 02:03
One way out, is to rename the settings file to something else and then reopen the app.
This file is located to your `C:\Users\YOUR_USERNAME\AppData\Roaming\KOHighlights\` folder.
You will lose your settings but not the database.

Another more advanced way to solve this, is to
- Open the settings file with 7zip
- Extract the `settings.json` file
- Change the "current_view" key to 0 (the Books view)
- Re-add the file to the settings file archive
- Save the changed file (always keep a backup)

I wonder what's wrong with the setup though.
The err_log file might be helpful.

Perhaps you can split your books to different databases (see [here](https://noembryo.github.io/KoHighlights/#database-management))
Depending on the number of the highlights, things can get difficult.

**Comment by edo-jan** [comment] 2024-11-01 02:08
Thanks for the info. Attached is the error log.
[error_log_2024-10-31.zip](https://github.com/user-attachments/files/17595139/error_log_2024-10-31.zip)

**Comment by noembryo** [comment] 2024-11-01 02:26
Try to use [this version](https://mega.nz/file/uI91hQhZ#4qp3jIIRV5Zq9uwcrgz259xb9oWumoPKrIrdQKcr0SE).
I think that the problem is the sorting by chapters..

**Comment by edo-jan** [comment] 2024-11-01 02:56
Version 2.2.2 fixed the issue. The program opened with new Letter icons (honestly, not a big fan of the new theme). When tried changing it to the good old "Light theme old icons" all icons disappeared. Restart did not help. ![2024-10-31_225039](https://github.com/user-attachments/assets/bea87f11-6404-4a52-9a57-18a92209245f).

**Comment by noembryo** [comment] 2024-11-01 03:09
Oups!!
Sorry for this, my fault.. 🤦‍♂️ 
Download [this version](https://mega.nz/file/TZdAGDCQ#24Btka2Uq8SJiWvRZQ-yBWMHB6pFG1A4KhSwKwqH808)..

**Comment by edo-jan** [comment] 2024-11-01 03:14
This one works ok - thank you!

**Comment by noembryo** [comment] 2024-11-03 23:42
Fixed in v2.3.0.0

**Closed by noembryo** 2024-11-03 23:42 UTC
